### ISSUE TITLE
How to use the model for testing single images with the pretrained model provided in the link.

### ISSUE THREAD

**Issue by chamorajg** [amirassov/kaggle-imaterialist#10]

**Comment by amirassov** [comment]
Hi, you can see an inference example in mmdetection docs: https://github.com/amirassov/kaggle-imaterialist/blob/master/mmdetection/GETTING_STARTED.md#high-level-apis-for-testing-images

**Comment by chamorajg** [comment]
yeah I used the same but that particular script uses cocoapi labels as default and not the labels used in kaggle. I want to use the attributes from the labels file.

**Comment by chamorajg** [comment]
@amirassov  Is your model trained to detect the attributes as well ? Or is it only the classes.

**Comment by amirassov** [comment]
You can get classes for my model from https://www.kaggle.com/c/imaterialist-fashion-2019-FGVC6/data (key `categories` of `label_descriptions.json`). 

Model trained to detect only categories.

**Comment by chamorajg** [comment]
@amirassov Thanks for the information. I will close this issue.
