### ISSUE TITLE
trained model checkpoint?

### ISSUE THREAD

**Issue by jaidmin** [amirassov/kaggle-imaterialist#2]
hi, congratulations on the kaggle win!

just wanted to ask if you can release the trained model, as I dont have the resources to train the model myself.

cheers

**Comment by ghunkins** [comment]
Hoping for this as well. Would be hugely helpful @amirassov!

**Comment by Steve1820** [comment]
Anyone kind enough to upload checkpoint/ saved weights?

Don't have the resources to run that many GPUs for 3 days :(

**Comment by amirassov** [comment]
@Steve1820 Hi, link to my best checkpoint: https://yadi.sk/d/-raqliq_ad6r_Q
