### ISSUE TITLE
Augmentation Code

### ISSUE THREAD

**Issue by heshuting555** [amirassov/kaggle-imaterialist#5]
It is a wonderful work! Can you provide the agmentation code. I don't know how to increase data augmentation in mmdetection. Waiting for your reply. Thank you for your help.
Thanks!

**Comment by amirassov** [comment]
Hello, you can see augmentation wrapper here: https://github.com/amirassov/kaggle-imaterialist/blob/master/mmdetection/mmdet/datasets/extra_aug.py#L8.

Augmentations here https://github.com/amirassov/kaggle-imaterialist/blob/master/configs/htc_dconv_c3-c5_mstrain_x101_64x4d_fpn_20e_1200x1900.py#L197-L220

**Comment by heshuting555** [comment]
Thank you for your reply. It is useful for me.




------------------ 原始邮件 ------------------
发件人: "Miras Amir"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上7:02
收件人: "amirassov/kaggle-imaterialist"<kaggle-imaterialist@noreply.github.com>;
抄送: "浮城﹋"<1173718914@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [amirassov/kaggle-imaterialist] Augmentation Code (#5)




Closed #5.
