### ISSUE TITLE
missing keys while loading weights and output coming empty array for all test images

### ISSUE THREAD

**Issue by lucky630** [amirassov/kaggle-imaterialist#6]

**Comment by lucky630** [comment]
Hi @amirassov ,

i am facing below problem while loading the weights for the model.

missing keys in source state_dict: bbox_head.0.fc_reg.bias, bbox_head.1.fc_cls.bias, mask_head.2.conv_res.conv.bias, bbox_head.2.fc_cls.weight, bbox_head.0.shared_fcs.0.bias, mask_head.1.convs.1.conv.weight, mask_head.0.conv_res.conv.weight, mask_head.1.convs.1.conv.bias, mask_head.1.convs.0.conv.bias, mask_head.0.convs.2.conv.weight, mask_head.0.conv_res.conv.bias, mask_head.0.convs.3.conv.weight, mask_head.2.convs.1.conv.weight, mask_head.2.convs.0.conv.weight, mask_head.1.conv_res.conv.weight, mask_head.1.convs.2.conv.weight, mask_head.0.convs.1.conv.bias, bbox_head.2.fc_reg.weight, mask_head.1.conv_res.conv.bias, mask_head.1.conv_logits.bias, mask_head.0.convs.0.conv.weight, bbox_head.1.shared_fcs.0.bias, mask_head.2.upsample.weight, bbox_head.0.fc_cls.bias, mask_head.2.conv_logits.weight, mask_head.0.conv_logits.weight, mask_head.0.convs.1.conv.weight, mask_head.1.convs.0.conv.weight, bbox_head.1.fc_cls.weight, bbox_head.2.fc_reg.bias, bbox_head.0.fc_cls.weight, bbox_head.2.shared_fcs.0.bias, mask_head.2.conv_res.conv.weight, bbox_head.1.fc_reg.weight, bbox_head.1.shared_fcs.1.bias, mask_head.2.convs.0.conv.bias, bbox_head.0.shared_fcs.1.bias, mask_head.1.convs.3.conv.bias, mask_head.0.upsample.bias, bbox_head.1.fc_reg.bias, mask_head.2.convs.1.conv.bias, bbox_head.0.fc_reg.weight, mask_head.2.convs.3.conv.weight, mask_head.1.convs.2.conv.bias, mask_head.0.upsample.weight, mask_head.1.upsample.weight, mask_head.2.convs.2.conv.weight, bbox_head.1.shared_fcs.1.weight, mask_head.1.upsample.bias, bbox_head.2.shared_fcs.1.bias, mask_head.2.convs.3.conv.bias, mask_head.1.conv_logits.weight, bbox_head.2.shared_fcs.1.weight, mask_head.2.conv_logits.bias, mask_head.2.upsample.bias, mask_head.1.convs.3.conv.weight, mask_head.0.convs.2.conv.bias, bbox_head.0.shared_fcs.1.weight, mask_head.2.convs.2.conv.bias, mask_head.0.conv_logits.bias, bbox_head.0.shared_fcs.0.weight, bbox_head.2.shared_fcs.0.weight, mask_head.0.convs.3.conv.bias, mask_head.0.convs.0.conv.bias, bbox_head.1.shared_fcs.0.weight, bbox_head.2.fc_cls.bias

i was running the dist_test.sh script with following parameters
bash dist_test.sh /kaggle-imaterialist/configs/htc_dconv_c3-c5_mstrain_x101_64x4d_fpn_20e_1200x1900.py /dumps/htc_dconv_c3-c5_mstrain_x101_64x4d_fpn_20e_1200x1900/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e_20190408-0e50669c_prune.pth 1

Thanks,
Gurvinder

**Comment by amirassov** [comment]
When you use script https://github.com/amirassov/kaggle-imaterialist/blob/master/src/prune.py, weights of bbox_head and mask_head is pruned. So this keys are missed in state_dict.

**Comment by lucky630** [comment]
okay so the weights are pretrained on Coco Dataset and we are fine tuning to make it work on this fashion dataset. so if we directly use these weights for inferencing then we get empty array as output.No got it.
by the way,I tried to train the weights but it is showing 12 hours for single epoch on 1 v100 gpu.
and training failed due to some bad image in the training set. should catch the exception before start training.
